spring.application.name=wego-backend
server.port=8081

#db
#spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
#spring.datasource.username=postgres.japawlwwzigdlthvtgah
#spring.datasource.password=L@ngSupa216
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/Wego
spring.datasource.username=postgres
spring.datasource.password=210605
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Disable default Spring Security password
spring.security.user.password=disabled

# JWT
jwt.secret=wego-secret-key-123456789012345678901234
jwt.expiration-ms=86400000

# Goole
google.map.key=AIzaSyCwwQbfJG8GD3fYXC8Yy9n0_qz6oMe33Qw

