spring.application.name=wego-backend
server.port=${PORT:8082}

#db
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.japawlwwzigdlthvtgah
spring.datasource.password=L@ngSupa216
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://localhost:5432/Wego
#spring.datasource.username=postgres
#spring.datasource.password=210605
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Disable default Spring Security password
spring.security.user.password=disabled

# JWT
jwt.secret=wego-secret-key-123456789012345678901234
jwt.expiration-ms=86400000

# Map
goong.api.key=cRdymyCCWWG00GcCHyFquAje53JTQMEprUxBmSAH
serp.api.key=bb8e1b09177c0b1422379a77316afb0662146dbf2bfb9ac1bf041c5d29629605

#auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-cl6n70h2qmq3y0b2.us.auth0.com/

#AI
ai.service.url=https://wego-ai.onrender.com

